task :default => [:ci, :jci]


task :ci do
  sh 'spec spec'
end

task :jci do
  unless (which_jruby = `which jruby`).empty?
    jruby_bin_dir = File.dirname(which_jruby)
    sh "#{jruby_bin_dir}/spec spec"
  else
    puts "jruby was not found in PATH (`which jruby` gives nothing)"
  end
end
