task :default => [:status, :ci, :jci, :bench]

task :status do
  o = `git-log | grep oleganza -c`.to_i
  y = `git-log | grep yrashk -c`.to_i
  sum = o + y
  op = (o*100.0/sum).round
  yp = (y*100.0/sum).round
  puts ""
  puts "        Commit status        "
  puts "--------             --------"
  puts "oleganza  #{op}% — #{yp}%  yrashk"
  puts ""
end

task :bench => [:benchmarks]
task :benchmarks do
  paths = Dir['test/**/*_benchmark.rb']
  paths.each do |path| 
    ruby path
    puts ""
  end
end

task :ci do
  sh 'spec spec'
end

task :jci do
  unless (which_jruby = `which jruby`).empty?
    jruby_bin_dir = File.dirname(which_jruby)
    sh "#{jruby_bin_dir}/spec spec"
  else
    puts "jruby was not found in PATH (`which jruby` gives nothing)"
  end
end
