require 'rake'
require 'rubygems'
require 'spec/rake/spectask'

require 'rake/rdoctask'

task :default => [:ci, :jci, :bench]

task :bench => [:benchmarks]
task :benchmarks do
  paths = Dir['benchmarks/**/*.rb']
  paths.each do |path| 
    ruby path
    puts ("-"*80)+"\n "
  end
end

task :ci do
  sh 'spec spec'
end

task :ci_indefinitely do
   i=0;loop{i+=1;puts i ; t=`spec spec`;if t =~ /[\.F]F|F[\.F]/ ; puts t ; break ; end }
end

task :jci do
  unless (which_jruby = `which jruby`).empty?
    jruby_bin_dir = File.dirname(which_jruby)
    sh "#{jruby_bin_dir}/spec spec"
  else
    puts "jruby was not found in PATH (`which jruby` gives nothing)"
  end
end

desc "Run all examples with RCov"
Spec::Rake::SpecTask.new('spec_rcov') do |t|
  t.spec_files = FileList['spec/**/*.rb']
  t.rcov = true
  t.rcov_opts = ['--exclude', 'spec,strokedb.rb','--sort','coverage','--xrefs']
end

STATS_DIRECTORIES = [
  %w(Code        lib),
  %w(Specs       spec)
].collect { |name, dir| [ name, "#{File.dirname(__FILE__)}/#{dir}" ] }.select { |name, dir| File.directory?(dir) }

desc "Report code statistics (KLOCs, etc) from the application"
task :stats do
  require 'code_statistics'
  CodeStatistics.const_set(:TEST_TYPES,%w(Specs))
  CodeStatistics.new(*STATS_DIRECTORIES).to_s
end

Rake::RDocTask.new do |rd|
   rd.main = "README"
   rd.rdoc_dir = "docs/html"
   rd.rdoc_files.include("README", "lib/**/*.rb")
end
